# Strong scaling — 4 nodes, 6 GPUs/node  (total: 24 GPUs, 4 islands, 25k gens/island)
# MAX_GENERATIONS=100000 divided by world_size=4 => 25000 gens per island
# sbatch --nodes=4 --ntasks-per-node=1 --gres=gpu:6 run.sbatch config/strong_scaling_4n6g.conf

RUN_PREFIX = strong-8n6g

TARGET_FILE = input/strong_scaling.ppm

N_TRIANGLES = 300
POP_SIZE = 100
DISC_COUNT = 0
MAX_GENERATIONS = 100000
STAGNATION_GENS = 0
STAGNATION_RELATIVE = 0
STAGNATION_ABS_TOL = 1e-7
STAGNATION_REL_TOL = 1e-4
CROSSOVER_PROB = 0.95
ALPHA_INIT = 0.15
LOSS_TYPE = mse
WMSE_POWER = 1
NUM_GPUS = 0
MIGRATION_INTERVAL = 100
MIGRATION_SIZE = 1
VISUALISE_EVERY = 10000
